#!/usr/bin/python

# Copyright Janne Blomqvist (C) 2009

# Convert angle potential table from Espresso format to Gromacs.

import math
from params import *
import numpy as np
        
def espresso2gro_convert_table(fin, fout, plot=False):
    if isinstance(fin, str):
        fin = open(fin)
    if isinstance(fout, str):
        fout = open(fout, 'w')
    pots = []
    for line in fin:
        if line.startswith('#'):
            fout.write(line)
        else:
            angle, force, pot = [float(x) for x in line.split()]
            angle = angle * 180. / math.pi
            pots.append((angle, pot, -force))

    # Espresso tables don't contain the 0.0 angle, insert it manually
    # It's practically never going to happen, so the actual values
    # don't matter that much. I.e. don't bother with some fancy
    # extrapolation scheme.
    pots.insert(0, (0.0, pots[0][1], pots[0][2]))
    
    pots = np.asarray(pots)
    for line in pots:
        # As the forces in Espresso tables are suspiciously noisy,
        # just let Gromacs use forces generated by taking the
        # numerical derivative of the potential (set force=0 in table)
        fout.write("%20.10f  %20.12f  %20.12f\n" % (line[0], line[1], 0.0))
    
    # Calculate expectation value from distribution
    # Distribution is Boltzmann inversion of potential
    
    # Ignore the partition function Q, we're just interested in
    # the shape of the distribution
    
    w = np.exp(-pots[:,1]/kb/temp)
    norm = np.sum(w)
    kernel = pots[:,0] * w / norm
    eval = np.sum(kernel)
    if plot:
        import pylab
        pylab.plot(pots[:,0], pots[:,1], label='Potential')
        pylab.plot(pots[:,0], pots[:,2], label='Force')
        pylab.plot(pots[:,0], w*50, label='Distribution (scaled x50)')
        pylab.legend()
        pylab.xlim(0, 180)
        pylab.show()
    return eval

if __name__=="__main__":
    import sys
    if len(sys.argv) > 2:
        fout = open(sys.argv[2], 'w')
    else:
        fout = sys.stdout
    eval = espresso2gro_convert_table(sys.argv[1], fout, True)
    print 'Expectation value: ', eval
